# Generated by Django 2.2.6 on 2019-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191011_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='loft_size',
            new_name='lot_size',
        ),
    ]
