# Generated by Django 2.2.6 on 2019-10-14 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191011_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='state',
            new_name='country',
        ),
    ]
